settings:
  title: 'Status Page'
  url: 'https://status-page.jyi.tw' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: '託管平臺狀態.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: jyi-tw
    name: jyi.tw
    url: 'https://www.jyi.tw/'
    method: GET
    expectStatus: 200  
    
  - id: www-jyi-tw
    name: www.jyi.tw
    url: 'https://www.jyi.tw/'
    method: GET
    expectStatus: 200
    
  - id: camunda-jyi-tw
    name: camunda.jyi.tw
    url: 'https://camunda.jyi.tw/'
    method: GET
    expectStatus: 200
    
  - id: java-jyi-tw
    name: java.jyi.tw
    url: 'https://java.jyi.tw/'
    method: GET
    expectStatus: 200
    
  - id: bookjournal-jyi-tw
    name: bookjournal.jyi.tw
    url: 'https://bookjournal.jyi.tw/'
    method: GET
    expectStatus: 200
